const ROUTES = {
    HOME: "/",
    ROOMS: "/rooms",
    WINE_DINE: "/wine_dine",
    HEALTH_CARE: "/health_care",
    SPECIAL_OFFERS: "/special_offers",
    ABOUT_US: "/about_us",
    SIGN_IN: "/sign-in",
    SIGN_UP: "/sign-up",
    SIGN_IN_WITH_OAUTH: "/signin-with-oauth",
    PAYMENT: "/payment",
    PAYMENT_SUCCESS: "/payment/success",
    ADMIN: "/admin",
    ADMIN_OVERVIEW: "/admin/overview",
    ADMIN_BOOKINGS: "/admin/bookings",
    ADMIN_PAYMENTS: "/admin/payments",
    ADMIN_BRANCHES: "/admin/branches",
    ADMIN_ROOMS: "/admin/rooms",
    ADMIN_GUESTS: "/admin/guests",
    ADMIN_STAFF: "/admin/staff",
    ADMIN_BILLS: "/admin/bills",
    ADMIN_ANALYTICS: "/admin/analytics",
    ADMIN_NOTIFICATIONS: "/admin/notifications",
    ADMIN_SETTINGS: "/admin/settings",
    RECEPTIONIST: "/receptionist",
    RECEPTIONIST_OVERVIEW: "/receptionist/overview",
    RECEPTIONIST_BOOKINGS: "/receptionist/bookings",
    RECEPTIONIST_BILLS: "/receptionist/bills",
    RECEPTIONIST_GUESTS: "/receptionist/guests",
    RECEPTIONIST_ROOMS: "/receptionist/rooms",
}

export default ROUTES;