import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar_for_homepage";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { Providers } from "./providers";
import Footer from "@/components/footer/page";

export const metadata: Metadata = {
  title: "Hô teo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={``}> 
      <SessionProvider>
        <Providers>
          <body className="flex flex-col min-h-screen"> 
            <main className="flex-grow">
              {children}
              <Toaster/>
            </main>
          </body>
        </Providers>
      </SessionProvider>
    </html>
  );
}