import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { Providers } from "./providers";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Hô teo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={``}> 
      <SessionProvider>
        <Providers>
          <Suspense>
            <body className="flex flex-col min-h-screen"> 
              <main className="flex-grow">
                {children}
                <Toaster/>
              </main>
            </body>
          </Suspense>
        </Providers>
      </SessionProvider>
    </html>
  );
}