import Footer from "@/components/footer/footer_for_homepage/page";
import ClientNavbar from "@/components/navbar/navbar_for_homepage/ClientNavbarForHomePage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hô teo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en" className={``}> 
        <ClientNavbar/>
        {children}
        <Footer />
    </div>
  );
}